config/routes.rb
Rails.application.routes.draw do
  resources :eventos
  resources :user_sessions
  resources :users
  
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users
  resources :eventos do
    resources :lances
  end
  root 'eventos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evento.rb
class Evento < ApplicationRecord
    #belongs_to :user
    has_many :lances
    validates  :marca, presence: true
    validates  :modelo, presence: true
    validates  :ano, presence: true
    validates  :combustivel, presence: true
    validates  :valor, presence: true
end

app/models/lance.rb
class Lance < ApplicationRecord
  belongs_to :evento
end

app/models/user.rb
class User < ApplicationRecord
    authenticates_with_sorcery!
    
    validates :nome, presence: true
    validates :sobrenome, presence: true
    validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
    validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
    validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  
    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:status, :usuario, :marca, :modelo, :ano, :combustivel, :valor, :fim)
    end
end

app/controllers/lances_controller.rb
class LancesController < ApplicationController
    def create
        @evento = Evento.find(params[:evento_id])

        @lance = @evento.lances.create(lance_params)

        redirect_to evento_path(@evento)
    end

    private
        def lance_params
            params.require(:lance).permit(:nome,:valor)
        end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create, :show]
  #before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find params[:id]
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :users, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    if @user.present?
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
    
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :sobrenome, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/lances_helper.rb
module LancesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/eventos/_form.html.erb
<%= form_with(model: evento, local: true) do |form| %>
  <% if evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :evento_status %>
  </div>

  <div class="field">
    <%= form.label :usuario %>
    <%# :usuario @user.nome %>
    <%= form.text_field :usuario, id: :evento_usuario %>
  </div>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca, id: :evento_marca %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo, id: :evento_modelo %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :evento_ano %>
  </div>

  <div class="field">
    <%= form.label :combustivel %>
    <%= form.text_field :combustivel, id: :evento_combustivel %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor, id: :evento_valor %>
  </div>

  <div class="field">
    <%= form.label :fim %>
    <%= form.time_select :fim, id: :evento_fim %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Usuario</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Ano</th>
      <th>Combustivel</th>
      <th>Valor</th>
      <th>Fim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.status %></td>
        <td><%= evento.usuario %></td>
        <td><%= evento.marca %></td>
        <td><%= evento.modelo %></td>
        <td><%= evento.ano %></td>
        <td><%= evento.combustivel %></td>
        <td><%= evento.valor %></td>
        <td><%= evento.fim %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @evento.status %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @evento.usuario %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @evento.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @evento.modelo %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @evento.ano %>
</p>

<p>
  <strong>Combustivel:</strong>
  <%= @evento.combustivel %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @evento.valor %>
</p>

<p>
  <strong>Fim:</strong>
  <%= @evento.fim %>
</p>

<br />

<h2>Lances</h2>
<% @evento.lances.each do |lance| %>
<p>
  <strong>Nome:</strong>
  <%= lance.nome %>
</p>
<p>
  <strong>Lance:</strong>
  <%= number_with_precision(lance.valor, :precision => 2) %>
</p>
<% end %>

<br />
<br />

<h2>Fazer um Lance:</h2>
<%= form_for([@evento,@evento.lances.build]) do |f| %>
  <p>
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </p>
  <p>
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </p>
<p>
  <%= f.submit %>
</p>
<% end %>


<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leilao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="nav">
      <% if current_user %>
        <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
        <%= link_to "Logout", :logout, method: :post %>
      <% else %>
        <%= link_to "Register", new_user_path %> |
        <%= link_to "Login", :login %>
      <% end %>
    </div>
    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email %><br />
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %><br />
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Login" %>
    </div>
  <% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :user_nome %>
  </div>

  <div class="field">
    <%= form.label :sobrenome %>
    <%= form.text_field :sobrenome, id: :user_sobrenome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', eventos_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nome %></td>
        <td><%= user.sobrenome %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', eventos_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @user.sobrenome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', eventos_path %>